# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'concept_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 601)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_header.setStyleSheet("QFrame{\n"
"    border-bottom: 1px solid #000;\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.main_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tittle_bar_container = QtWidgets.QFrame(self.main_header)
        self.tittle_bar_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tittle_bar_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tittle_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar_container.setObjectName("tittle_bar_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tittle_bar_container)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_menu_toggle = QtWidgets.QFrame(self.tittle_bar_container)
        self.left_menu_toggle.setMinimumSize(QtCore.QSize(50, 50))
        self.left_menu_toggle.setMaximumSize(QtCore.QSize(50, 50))
        self.left_menu_toggle.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"}")
        self.left_menu_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_menu_toggle.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.left_menu_toggle.setObjectName("left_menu_toggle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.left_menu_toggle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.left_menu_toggle)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout_5.addWidget(self.left_menu_toggle)
        self.tittle_bar = QtWidgets.QFrame(self.tittle_bar_container)
        self.tittle_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tittle_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar.setObjectName("tittle_bar")
        self.horizontalLayout_5.addWidget(self.tittle_bar)
        self.horizontalLayout_2.addWidget(self.tittle_bar_container)
        self.top_right_btns = QtWidgets.QFrame(self.main_header)
        self.top_right_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.top_right_btns.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.top_right_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_right_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimizeButton = QtWidgets.QPushButton(self.top_right_btns)
        self.minimizeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon1)
        self.minimizeButton.setIconSize(QtCore.QSize(24, 24))
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_3.addWidget(self.minimizeButton)
        self.restoreButton = QtWidgets.QPushButton(self.top_right_btns)
        self.restoreButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreButton.setIcon(icon2)
        self.restoreButton.setIconSize(QtCore.QSize(24, 24))
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout_3.addWidget(self.restoreButton)
        self.closeButton = QtWidgets.QPushButton(self.top_right_btns)
        self.closeButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon3)
        self.closeButton.setIconSize(QtCore.QSize(24, 24))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.horizontalLayout_2.addWidget(self.top_right_btns)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        self.left_side_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_side_menu.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"}\n"
"QPushButton:text{\n"
"    padding-left: 50px\n"
"}")
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_menu_top_buttons = QtWidgets.QFrame(self.left_side_menu)
        self.left_menu_top_buttons.setMinimumSize(QtCore.QSize(50, 0))
        self.left_menu_top_buttons.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.left_menu_top_buttons.setStyleSheet("")
        self.left_menu_top_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_top_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_top_buttons.setObjectName("left_menu_top_buttons")
        self.formLayout = QtWidgets.QFormLayout(self.left_menu_top_buttons)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.sensors_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.sensors_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensors_button.sizePolicy().hasHeightForWidth())
        self.sensors_button.setSizePolicy(sizePolicy)
        self.sensors_button.setMinimumSize(QtCore.QSize(50, 50))
        self.sensors_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setKerning(False)
        self.sensors_button.setFont(font)
        self.sensors_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sensors_button.setStyleSheet("background-image: url(:/icons/icons/cil-rss.png);\n"
"background-repeat: none;\n"
"background-position: center;\n"
"")
        self.sensors_button.setText("")
        self.sensors_button.setDefault(False)
        self.sensors_button.setObjectName("sensors_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.sensors_button)
        self.reports_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.reports_button.setMinimumSize(QtCore.QSize(50, 50))
        self.reports_button.setStyleSheet("background-image: url(:/icons/icons/cil-screen-desktop.png);\n"
"background-repeat: none;\n"
"background-position: center;")
        self.reports_button.setText("")
        self.reports_button.setObjectName("reports_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.reports_button)
        self.verticalLayout_2.addWidget(self.left_menu_top_buttons)
        self.settings_button = QtWidgets.QPushButton(self.left_side_menu)
        self.settings_button.setMinimumSize(QtCore.QSize(50, 50))
        self.settings_button.setStyleSheet("background-image: url(:/icons/icons/cil-settings.png);\n"
"background-repeat: none;\n"
"background-position: center;")
        self.settings_button.setText("")
        self.settings_button.setObjectName("settings_button")
        self.verticalLayout_2.addWidget(self.settings_button)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.center_main_menu = QtWidgets.QFrame(self.main_body)
        self.center_main_menu.setStyleSheet("")
        self.center_main_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_main_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_main_menu.setObjectName("center_main_menu")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.center_main_menu)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.center_main_menu)
        self.stackedWidget.setStyleSheet("QPushButton{\n"
"    background-color: rgb(4, 44, 103);\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.sensors_page = QtWidgets.QWidget()
        self.sensors_page.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"\n"
"")
        self.sensors_page.setObjectName("sensors_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.sensors_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sensors_stacked_widget = QtWidgets.QStackedWidget(self.sensors_page)
        self.sensors_stacked_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sensors_stacked_widget.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"")
        self.sensors_stacked_widget.setObjectName("sensors_stacked_widget")
        self.sensor1_page = QtWidgets.QWidget()
        self.sensor1_page.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"")
        self.sensor1_page.setObjectName("sensor1_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sensor1_page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sensor1_main_frame = QtWidgets.QFrame(self.sensor1_page)
        self.sensor1_main_frame.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"")
        self.sensor1_main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensor1_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor1_main_frame.setObjectName("sensor1_main_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.sensor1_main_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sensor1_header = QtWidgets.QFrame(self.sensor1_main_frame)
        self.sensor1_header.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sensor1_header.setStyleSheet("QPushButton{\n"
"    background-color: rgb(34, 34, 34);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}\n"
"QLabel{\n"
"    background-color: rgb(34, 34, 34);\n"
"}\n"
"")
        self.sensor1_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor1_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor1_header.setObjectName("sensor1_header")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.sensor1_header)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sensor1_prev_btn = QtWidgets.QPushButton(self.sensor1_header)
        self.sensor1_prev_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.sensor1_prev_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor1_prev_btn.setStyleSheet("")
        self.sensor1_prev_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/cil-arrow-circle-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sensor1_prev_btn.setIcon(icon4)
        self.sensor1_prev_btn.setIconSize(QtCore.QSize(24, 24))
        self.sensor1_prev_btn.setObjectName("sensor1_prev_btn")
        self.horizontalLayout_8.addWidget(self.sensor1_prev_btn)
        self.sensor1_label = QtWidgets.QLabel(self.sensor1_header)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.sensor1_label.setFont(font)
        self.sensor1_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor1_label.setObjectName("sensor1_label")
        self.horizontalLayout_8.addWidget(self.sensor1_label)
        self.sensor1_next_btn = QtWidgets.QPushButton(self.sensor1_header)
        self.sensor1_next_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.sensor1_next_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor1_next_btn.setStyleSheet("")
        self.sensor1_next_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/cil-arrow-circle-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sensor1_next_btn.setIcon(icon5)
        self.sensor1_next_btn.setIconSize(QtCore.QSize(24, 24))
        self.sensor1_next_btn.setObjectName("sensor1_next_btn")
        self.horizontalLayout_8.addWidget(self.sensor1_next_btn)
        self.verticalLayout_6.addWidget(self.sensor1_header)
        self.sensor1_body = QtWidgets.QFrame(self.sensor1_main_frame)
        self.sensor1_body.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-radius: 5px;")
        self.sensor1_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensor1_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor1_body.setObjectName("sensor1_body")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.sensor1_body)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.sensor1_details_frame = QtWidgets.QFrame(self.sensor1_body)
        self.sensor1_details_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sensor1_details_frame.setStyleSheet("")
        self.sensor1_details_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor1_details_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor1_details_frame.setObjectName("sensor1_details_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.sensor1_details_frame)
        self.horizontalLayout_6.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sensor1_temp_frame = QtWidgets.QFrame(self.sensor1_details_frame)
        self.sensor1_temp_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor1_temp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor1_temp_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor1_temp_frame.setObjectName("sensor1_temp_frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.sensor1_temp_frame)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sensor1_temp_label = QtWidgets.QLabel(self.sensor1_temp_frame)
        self.sensor1_temp_label.setMinimumSize(QtCore.QSize(0, 0))
        self.sensor1_temp_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor1_temp_label.setObjectName("sensor1_temp_label")
        self.horizontalLayout_9.addWidget(self.sensor1_temp_label)
        self.sensor1_temp_value = QtWidgets.QLabel(self.sensor1_temp_frame)
        self.sensor1_temp_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor1_temp_value.setText("")
        self.sensor1_temp_value.setObjectName("sensor1_temp_value")
        self.horizontalLayout_9.addWidget(self.sensor1_temp_value)
        self.sensor1_temp_trend_btn = QtWidgets.QPushButton(self.sensor1_temp_frame)
        self.sensor1_temp_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor1_temp_trend_btn.setStyleSheet("background:hover{\n"
"    \n"
"}")
        self.sensor1_temp_trend_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/cil-chart-line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sensor1_temp_trend_btn.setIcon(icon6)
        self.sensor1_temp_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor1_temp_trend_btn.setObjectName("sensor1_temp_trend_btn")
        self.horizontalLayout_9.addWidget(self.sensor1_temp_trend_btn)
        self.horizontalLayout_6.addWidget(self.sensor1_temp_frame)
        self.sensor1_humidity_frame = QtWidgets.QFrame(self.sensor1_details_frame)
        self.sensor1_humidity_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor1_humidity_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor1_humidity_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor1_humidity_frame.setObjectName("sensor1_humidity_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.sensor1_humidity_frame)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sensor1_humidity_label = QtWidgets.QLabel(self.sensor1_humidity_frame)
        self.sensor1_humidity_label.setMaximumSize(QtCore.QSize(46, 16777215))
        self.sensor1_humidity_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor1_humidity_label.setObjectName("sensor1_humidity_label")
        self.horizontalLayout_10.addWidget(self.sensor1_humidity_label)
        self.sensor1_humidity_value = QtWidgets.QLabel(self.sensor1_humidity_frame)
        self.sensor1_humidity_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor1_humidity_value.setText("")
        self.sensor1_humidity_value.setObjectName("sensor1_humidity_value")
        self.horizontalLayout_10.addWidget(self.sensor1_humidity_value)
        self.sensor1_humidity_trend_btn = QtWidgets.QPushButton(self.sensor1_humidity_frame)
        self.sensor1_humidity_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor1_humidity_trend_btn.setStyleSheet("")
        self.sensor1_humidity_trend_btn.setText("")
        self.sensor1_humidity_trend_btn.setIcon(icon6)
        self.sensor1_humidity_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor1_humidity_trend_btn.setObjectName("sensor1_humidity_trend_btn")
        self.horizontalLayout_10.addWidget(self.sensor1_humidity_trend_btn)
        self.horizontalLayout_6.addWidget(self.sensor1_humidity_frame)
        self.sensor1_CO2_frame = QtWidgets.QFrame(self.sensor1_details_frame)
        self.sensor1_CO2_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor1_CO2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor1_CO2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor1_CO2_frame.setObjectName("sensor1_CO2_frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.sensor1_CO2_frame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.sensor1_co2_label = QtWidgets.QLabel(self.sensor1_CO2_frame)
        self.sensor1_co2_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor1_co2_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor1_co2_label.setObjectName("sensor1_co2_label")
        self.horizontalLayout_11.addWidget(self.sensor1_co2_label)
        self.sensor1_co2_value = QtWidgets.QLabel(self.sensor1_CO2_frame)
        self.sensor1_co2_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor1_co2_value.setText("")
        self.sensor1_co2_value.setObjectName("sensor1_co2_value")
        self.horizontalLayout_11.addWidget(self.sensor1_co2_value)
        self.sensor1_co2_trend_btn = QtWidgets.QPushButton(self.sensor1_CO2_frame)
        self.sensor1_co2_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor1_co2_trend_btn.setStyleSheet("")
        self.sensor1_co2_trend_btn.setText("")
        self.sensor1_co2_trend_btn.setIcon(icon6)
        self.sensor1_co2_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor1_co2_trend_btn.setObjectName("sensor1_co2_trend_btn")
        self.horizontalLayout_11.addWidget(self.sensor1_co2_trend_btn)
        self.horizontalLayout_6.addWidget(self.sensor1_CO2_frame)
        self.sensor1_status_frame = QtWidgets.QFrame(self.sensor1_details_frame)
        self.sensor1_status_frame.setStyleSheet("background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;")
        self.sensor1_status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor1_status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor1_status_frame.setObjectName("sensor1_status_frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.sensor1_status_frame)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sensor1_status_label = QtWidgets.QLabel(self.sensor1_status_frame)
        self.sensor1_status_label.setMaximumSize(QtCore.QSize(35, 16777215))
        self.sensor1_status_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor1_status_label.setObjectName("sensor1_status_label")
        self.horizontalLayout_12.addWidget(self.sensor1_status_label)
        self.sensor1_status_value = QtWidgets.QLabel(self.sensor1_status_frame)
        self.sensor1_status_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor1_status_value.setText("")
        self.sensor1_status_value.setObjectName("sensor1_status_value")
        self.horizontalLayout_12.addWidget(self.sensor1_status_value)
        self.horizontalLayout_6.addWidget(self.sensor1_status_frame)
        self.verticalLayout_8.addWidget(self.sensor1_details_frame)
        self.sensor1_MplWidget = MplWidget(self.sensor1_body)
        self.sensor1_MplWidget.setObjectName("sensor1_MplWidget")
        self.verticalLayout_8.addWidget(self.sensor1_MplWidget)
        self.verticalLayout_6.addWidget(self.sensor1_body)
        self.verticalLayout_7.addWidget(self.sensor1_main_frame)
        self.sensors_stacked_widget.addWidget(self.sensor1_page)
        self.sensor2_page = QtWidgets.QWidget()
        self.sensor2_page.setObjectName("sensor2_page")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.sensor2_page)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.sensor2_main_frame = QtWidgets.QFrame(self.sensor2_page)
        self.sensor2_main_frame.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"")
        self.sensor2_main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensor2_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor2_main_frame.setObjectName("sensor2_main_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.sensor2_main_frame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sensor2_header = QtWidgets.QFrame(self.sensor2_main_frame)
        self.sensor2_header.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sensor2_header.setStyleSheet("QPushButton{\n"
"    background-color: rgb(34, 34, 34);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}\n"
"QLabel{\n"
"    background-color: rgb(34, 34, 34);\n"
"}\n"
"")
        self.sensor2_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor2_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor2_header.setObjectName("sensor2_header")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.sensor2_header)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.sensor2_prev_btn = QtWidgets.QPushButton(self.sensor2_header)
        self.sensor2_prev_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.sensor2_prev_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor2_prev_btn.setStyleSheet("")
        self.sensor2_prev_btn.setText("")
        self.sensor2_prev_btn.setIcon(icon4)
        self.sensor2_prev_btn.setIconSize(QtCore.QSize(24, 24))
        self.sensor2_prev_btn.setObjectName("sensor2_prev_btn")
        self.horizontalLayout_13.addWidget(self.sensor2_prev_btn)
        self.sensor2_label = QtWidgets.QLabel(self.sensor2_header)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.sensor2_label.setFont(font)
        self.sensor2_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor2_label.setObjectName("sensor2_label")
        self.horizontalLayout_13.addWidget(self.sensor2_label)
        self.sensor2_next_btn = QtWidgets.QPushButton(self.sensor2_header)
        self.sensor2_next_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.sensor2_next_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor2_next_btn.setStyleSheet("")
        self.sensor2_next_btn.setText("")
        self.sensor2_next_btn.setIcon(icon5)
        self.sensor2_next_btn.setIconSize(QtCore.QSize(24, 24))
        self.sensor2_next_btn.setObjectName("sensor2_next_btn")
        self.horizontalLayout_13.addWidget(self.sensor2_next_btn)
        self.verticalLayout_9.addWidget(self.sensor2_header)
        self.sensor2_body = QtWidgets.QFrame(self.sensor2_main_frame)
        self.sensor2_body.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-radius: 5px;")
        self.sensor2_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensor2_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor2_body.setObjectName("sensor2_body")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.sensor2_body)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.sensor2_details_frame = QtWidgets.QFrame(self.sensor2_body)
        self.sensor2_details_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sensor2_details_frame.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.sensor2_details_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor2_details_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor2_details_frame.setObjectName("sensor2_details_frame")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.sensor2_details_frame)
        self.horizontalLayout_14.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.sensor2_temp_frame = QtWidgets.QFrame(self.sensor2_details_frame)
        self.sensor2_temp_frame.setMaximumSize(QtCore.QSize(16777215, 1677215))
        self.sensor2_temp_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor2_temp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor2_temp_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor2_temp_frame.setObjectName("sensor2_temp_frame")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.sensor2_temp_frame)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.sensor2_temp_label = QtWidgets.QLabel(self.sensor2_temp_frame)
        self.sensor2_temp_label.setMinimumSize(QtCore.QSize(0, 0))
        self.sensor2_temp_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor2_temp_label.setObjectName("sensor2_temp_label")
        self.horizontalLayout_15.addWidget(self.sensor2_temp_label)
        self.sensor2_temp_value = QtWidgets.QLabel(self.sensor2_temp_frame)
        self.sensor2_temp_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor2_temp_value.setText("")
        self.sensor2_temp_value.setObjectName("sensor2_temp_value")
        self.horizontalLayout_15.addWidget(self.sensor2_temp_value)
        self.sensor2_temp_trend_btn = QtWidgets.QPushButton(self.sensor2_temp_frame)
        self.sensor2_temp_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor2_temp_trend_btn.setText("")
        self.sensor2_temp_trend_btn.setIcon(icon6)
        self.sensor2_temp_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor2_temp_trend_btn.setObjectName("sensor2_temp_trend_btn")
        self.horizontalLayout_15.addWidget(self.sensor2_temp_trend_btn)
        self.horizontalLayout_14.addWidget(self.sensor2_temp_frame)
        self.sensor2_humidity_frame = QtWidgets.QFrame(self.sensor2_details_frame)
        self.sensor2_humidity_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor2_humidity_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor2_humidity_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor2_humidity_frame.setObjectName("sensor2_humidity_frame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.sensor2_humidity_frame)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.sensor2_humidity_label = QtWidgets.QLabel(self.sensor2_humidity_frame)
        self.sensor2_humidity_label.setMaximumSize(QtCore.QSize(46, 16777215))
        self.sensor2_humidity_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor2_humidity_label.setObjectName("sensor2_humidity_label")
        self.horizontalLayout_16.addWidget(self.sensor2_humidity_label)
        self.sensor2_humidity_value = QtWidgets.QLabel(self.sensor2_humidity_frame)
        self.sensor2_humidity_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor2_humidity_value.setText("")
        self.sensor2_humidity_value.setObjectName("sensor2_humidity_value")
        self.horizontalLayout_16.addWidget(self.sensor2_humidity_value)
        self.sensor2_humidity_trend_btn = QtWidgets.QPushButton(self.sensor2_humidity_frame)
        self.sensor2_humidity_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor2_humidity_trend_btn.setText("")
        self.sensor2_humidity_trend_btn.setIcon(icon6)
        self.sensor2_humidity_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor2_humidity_trend_btn.setObjectName("sensor2_humidity_trend_btn")
        self.horizontalLayout_16.addWidget(self.sensor2_humidity_trend_btn)
        self.horizontalLayout_14.addWidget(self.sensor2_humidity_frame)
        self.sensor2_CO2_frame = QtWidgets.QFrame(self.sensor2_details_frame)
        self.sensor2_CO2_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor2_CO2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor2_CO2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor2_CO2_frame.setObjectName("sensor2_CO2_frame")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.sensor2_CO2_frame)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.sensor2_co2_label = QtWidgets.QLabel(self.sensor2_CO2_frame)
        self.sensor2_co2_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor2_co2_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor2_co2_label.setObjectName("sensor2_co2_label")
        self.horizontalLayout_17.addWidget(self.sensor2_co2_label)
        self.sensor2_co2_value = QtWidgets.QLabel(self.sensor2_CO2_frame)
        self.sensor2_co2_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor2_co2_value.setText("")
        self.sensor2_co2_value.setObjectName("sensor2_co2_value")
        self.horizontalLayout_17.addWidget(self.sensor2_co2_value)
        self.sensor2_co2_trend_btn = QtWidgets.QPushButton(self.sensor2_CO2_frame)
        self.sensor2_co2_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor2_co2_trend_btn.setText("")
        self.sensor2_co2_trend_btn.setIcon(icon6)
        self.sensor2_co2_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor2_co2_trend_btn.setObjectName("sensor2_co2_trend_btn")
        self.horizontalLayout_17.addWidget(self.sensor2_co2_trend_btn)
        self.horizontalLayout_14.addWidget(self.sensor2_CO2_frame)
        self.sensor2_status_frame = QtWidgets.QFrame(self.sensor2_details_frame)
        self.sensor2_status_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor2_status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor2_status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor2_status_frame.setObjectName("sensor2_status_frame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.sensor2_status_frame)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.sensor2_status_label = QtWidgets.QLabel(self.sensor2_status_frame)
        self.sensor2_status_label.setMaximumSize(QtCore.QSize(35, 16777215))
        self.sensor2_status_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor2_status_label.setObjectName("sensor2_status_label")
        self.horizontalLayout_18.addWidget(self.sensor2_status_label)
        self.sensor2_status_value = QtWidgets.QLabel(self.sensor2_status_frame)
        self.sensor2_status_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor2_status_value.setText("")
        self.sensor2_status_value.setObjectName("sensor2_status_value")
        self.horizontalLayout_18.addWidget(self.sensor2_status_value)
        self.horizontalLayout_14.addWidget(self.sensor2_status_frame)
        self.verticalLayout_10.addWidget(self.sensor2_details_frame)
        self.sensor2_MplWidget = MplWidget(self.sensor2_body)
        self.sensor2_MplWidget.setObjectName("sensor2_MplWidget")
        self.verticalLayout_10.addWidget(self.sensor2_MplWidget)
        self.verticalLayout_9.addWidget(self.sensor2_body)
        self.horizontalLayout_19.addWidget(self.sensor2_main_frame)
        self.sensors_stacked_widget.addWidget(self.sensor2_page)
        self.sensor3_page = QtWidgets.QWidget()
        self.sensor3_page.setObjectName("sensor3_page")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.sensor3_page)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.sensor3_main_frame = QtWidgets.QFrame(self.sensor3_page)
        self.sensor3_main_frame.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"")
        self.sensor3_main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensor3_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor3_main_frame.setObjectName("sensor3_main_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.sensor3_main_frame)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.sensor3_header = QtWidgets.QFrame(self.sensor3_main_frame)
        self.sensor3_header.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sensor3_header.setStyleSheet("QPushButton{\n"
"    background-color: rgb(34, 34, 34);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}\n"
"QLabel{\n"
"    background-color: rgb(34, 34, 34);\n"
"}\n"
"")
        self.sensor3_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor3_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor3_header.setObjectName("sensor3_header")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.sensor3_header)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.sensor3_prev_btn = QtWidgets.QPushButton(self.sensor3_header)
        self.sensor3_prev_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.sensor3_prev_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor3_prev_btn.setStyleSheet("")
        self.sensor3_prev_btn.setText("")
        self.sensor3_prev_btn.setIcon(icon4)
        self.sensor3_prev_btn.setIconSize(QtCore.QSize(24, 24))
        self.sensor3_prev_btn.setObjectName("sensor3_prev_btn")
        self.horizontalLayout_20.addWidget(self.sensor3_prev_btn)
        self.sensor3_label = QtWidgets.QLabel(self.sensor3_header)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.sensor3_label.setFont(font)
        self.sensor3_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor3_label.setObjectName("sensor3_label")
        self.horizontalLayout_20.addWidget(self.sensor3_label)
        self.sensor3_next_btn = QtWidgets.QPushButton(self.sensor3_header)
        self.sensor3_next_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.sensor3_next_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor3_next_btn.setStyleSheet("")
        self.sensor3_next_btn.setText("")
        self.sensor3_next_btn.setIcon(icon5)
        self.sensor3_next_btn.setIconSize(QtCore.QSize(24, 24))
        self.sensor3_next_btn.setObjectName("sensor3_next_btn")
        self.horizontalLayout_20.addWidget(self.sensor3_next_btn)
        self.verticalLayout_11.addWidget(self.sensor3_header)
        self.sensor3_body = QtWidgets.QFrame(self.sensor3_main_frame)
        self.sensor3_body.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-radius: 5px;")
        self.sensor3_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensor3_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor3_body.setObjectName("sensor3_body")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.sensor3_body)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.sensor3_details_frame = QtWidgets.QFrame(self.sensor3_body)
        self.sensor3_details_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sensor3_details_frame.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.sensor3_details_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor3_details_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor3_details_frame.setObjectName("sensor3_details_frame")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.sensor3_details_frame)
        self.horizontalLayout_21.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.sensor3_temp_frame = QtWidgets.QFrame(self.sensor3_details_frame)
        self.sensor3_temp_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor3_temp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor3_temp_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor3_temp_frame.setObjectName("sensor3_temp_frame")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.sensor3_temp_frame)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.sensor3_temp_label = QtWidgets.QLabel(self.sensor3_temp_frame)
        self.sensor3_temp_label.setMinimumSize(QtCore.QSize(0, 0))
        self.sensor3_temp_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor3_temp_label.setObjectName("sensor3_temp_label")
        self.horizontalLayout_22.addWidget(self.sensor3_temp_label)
        self.sensor3_temp_value = QtWidgets.QLabel(self.sensor3_temp_frame)
        self.sensor3_temp_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor3_temp_value.setText("")
        self.sensor3_temp_value.setObjectName("sensor3_temp_value")
        self.horizontalLayout_22.addWidget(self.sensor3_temp_value)
        self.sensor3_temp_trend_btn = QtWidgets.QPushButton(self.sensor3_temp_frame)
        self.sensor3_temp_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor3_temp_trend_btn.setText("")
        self.sensor3_temp_trend_btn.setIcon(icon6)
        self.sensor3_temp_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor3_temp_trend_btn.setObjectName("sensor3_temp_trend_btn")
        self.horizontalLayout_22.addWidget(self.sensor3_temp_trend_btn)
        self.horizontalLayout_21.addWidget(self.sensor3_temp_frame)
        self.sensor3_humidity_frame = QtWidgets.QFrame(self.sensor3_details_frame)
        self.sensor3_humidity_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor3_humidity_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor3_humidity_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor3_humidity_frame.setObjectName("sensor3_humidity_frame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.sensor3_humidity_frame)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.sensor3_humidity_label = QtWidgets.QLabel(self.sensor3_humidity_frame)
        self.sensor3_humidity_label.setMaximumSize(QtCore.QSize(46, 16777215))
        self.sensor3_humidity_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor3_humidity_label.setObjectName("sensor3_humidity_label")
        self.horizontalLayout_23.addWidget(self.sensor3_humidity_label)
        self.sensor3_humidity_value = QtWidgets.QLabel(self.sensor3_humidity_frame)
        self.sensor3_humidity_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor3_humidity_value.setText("")
        self.sensor3_humidity_value.setObjectName("sensor3_humidity_value")
        self.horizontalLayout_23.addWidget(self.sensor3_humidity_value)
        self.sensor3_humidity_trend_btn = QtWidgets.QPushButton(self.sensor3_humidity_frame)
        self.sensor3_humidity_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor3_humidity_trend_btn.setText("")
        self.sensor3_humidity_trend_btn.setIcon(icon6)
        self.sensor3_humidity_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor3_humidity_trend_btn.setObjectName("sensor3_humidity_trend_btn")
        self.horizontalLayout_23.addWidget(self.sensor3_humidity_trend_btn)
        self.horizontalLayout_21.addWidget(self.sensor3_humidity_frame)
        self.sensor3_CO2_frame = QtWidgets.QFrame(self.sensor3_details_frame)
        self.sensor3_CO2_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor3_CO2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor3_CO2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor3_CO2_frame.setObjectName("sensor3_CO2_frame")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.sensor3_CO2_frame)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.sensor3_co2_label = QtWidgets.QLabel(self.sensor3_CO2_frame)
        self.sensor3_co2_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor3_co2_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor3_co2_label.setObjectName("sensor3_co2_label")
        self.horizontalLayout_24.addWidget(self.sensor3_co2_label)
        self.sensor3_co2_value = QtWidgets.QLabel(self.sensor3_CO2_frame)
        self.sensor3_co2_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor3_co2_value.setText("")
        self.sensor3_co2_value.setObjectName("sensor3_co2_value")
        self.horizontalLayout_24.addWidget(self.sensor3_co2_value)
        self.sensor3_co2_trend_btn = QtWidgets.QPushButton(self.sensor3_CO2_frame)
        self.sensor3_co2_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor3_co2_trend_btn.setText("")
        self.sensor3_co2_trend_btn.setIcon(icon6)
        self.sensor3_co2_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor3_co2_trend_btn.setObjectName("sensor3_co2_trend_btn")
        self.horizontalLayout_24.addWidget(self.sensor3_co2_trend_btn)
        self.horizontalLayout_21.addWidget(self.sensor3_CO2_frame)
        self.sensor3_status_frame = QtWidgets.QFrame(self.sensor3_details_frame)
        self.sensor3_status_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor3_status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor3_status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor3_status_frame.setObjectName("sensor3_status_frame")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.sensor3_status_frame)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.sensor3_status_label = QtWidgets.QLabel(self.sensor3_status_frame)
        self.sensor3_status_label.setMaximumSize(QtCore.QSize(35, 16777215))
        self.sensor3_status_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor3_status_label.setObjectName("sensor3_status_label")
        self.horizontalLayout_25.addWidget(self.sensor3_status_label)
        self.sensor3_status_value = QtWidgets.QLabel(self.sensor3_status_frame)
        self.sensor3_status_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor3_status_value.setText("")
        self.sensor3_status_value.setObjectName("sensor3_status_value")
        self.horizontalLayout_25.addWidget(self.sensor3_status_value)
        self.horizontalLayout_21.addWidget(self.sensor3_status_frame)
        self.verticalLayout_12.addWidget(self.sensor3_details_frame)
        self.sensor3_MplWidget = MplWidget(self.sensor3_body)
        self.sensor3_MplWidget.setObjectName("sensor3_MplWidget")
        self.verticalLayout_12.addWidget(self.sensor3_MplWidget)
        self.verticalLayout_11.addWidget(self.sensor3_body)
        self.verticalLayout_13.addWidget(self.sensor3_main_frame)
        self.sensors_stacked_widget.addWidget(self.sensor3_page)
        self.sensor4_page = QtWidgets.QWidget()
        self.sensor4_page.setObjectName("sensor4_page")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.sensor4_page)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.sensor4_main_frame = QtWidgets.QFrame(self.sensor4_page)
        self.sensor4_main_frame.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"")
        self.sensor4_main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensor4_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor4_main_frame.setObjectName("sensor4_main_frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.sensor4_main_frame)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.sensor4_header = QtWidgets.QFrame(self.sensor4_main_frame)
        self.sensor4_header.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sensor4_header.setStyleSheet("QPushButton{\n"
"    background-color: rgb(34, 34, 34);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}\n"
"QLabel{\n"
"    background-color: rgb(34, 34, 34);\n"
"}\n"
"")
        self.sensor4_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor4_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor4_header.setObjectName("sensor4_header")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.sensor4_header)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.sensor4_prev_btn = QtWidgets.QPushButton(self.sensor4_header)
        self.sensor4_prev_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.sensor4_prev_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor4_prev_btn.setStyleSheet("")
        self.sensor4_prev_btn.setText("")
        self.sensor4_prev_btn.setIcon(icon4)
        self.sensor4_prev_btn.setIconSize(QtCore.QSize(24, 24))
        self.sensor4_prev_btn.setObjectName("sensor4_prev_btn")
        self.horizontalLayout_26.addWidget(self.sensor4_prev_btn)
        self.sensor4_label = QtWidgets.QLabel(self.sensor4_header)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.sensor4_label.setFont(font)
        self.sensor4_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor4_label.setObjectName("sensor4_label")
        self.horizontalLayout_26.addWidget(self.sensor4_label)
        self.sensor4_next_btn = QtWidgets.QPushButton(self.sensor4_header)
        self.sensor4_next_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.sensor4_next_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor4_next_btn.setStyleSheet("")
        self.sensor4_next_btn.setText("")
        self.sensor4_next_btn.setIcon(icon5)
        self.sensor4_next_btn.setIconSize(QtCore.QSize(24, 24))
        self.sensor4_next_btn.setObjectName("sensor4_next_btn")
        self.horizontalLayout_26.addWidget(self.sensor4_next_btn)
        self.verticalLayout_14.addWidget(self.sensor4_header)
        self.sensor4_body = QtWidgets.QFrame(self.sensor4_main_frame)
        self.sensor4_body.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"border-radius: 5px;")
        self.sensor4_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sensor4_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor4_body.setObjectName("sensor4_body")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.sensor4_body)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.sensor4_details_frame = QtWidgets.QFrame(self.sensor4_body)
        self.sensor4_details_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.sensor4_details_frame.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.sensor4_details_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor4_details_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor4_details_frame.setObjectName("sensor4_details_frame")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.sensor4_details_frame)
        self.horizontalLayout_27.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_27.setSpacing(6)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.sensor4_temp_frame = QtWidgets.QFrame(self.sensor4_details_frame)
        self.sensor4_temp_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor4_temp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor4_temp_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor4_temp_frame.setObjectName("sensor4_temp_frame")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.sensor4_temp_frame)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.sensor4_temp_label = QtWidgets.QLabel(self.sensor4_temp_frame)
        self.sensor4_temp_label.setMinimumSize(QtCore.QSize(0, 0))
        self.sensor4_temp_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor4_temp_label.setObjectName("sensor4_temp_label")
        self.horizontalLayout_28.addWidget(self.sensor4_temp_label)
        self.sensor4_temp_value = QtWidgets.QLabel(self.sensor4_temp_frame)
        self.sensor4_temp_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor4_temp_value.setText("")
        self.sensor4_temp_value.setObjectName("sensor4_temp_value")
        self.horizontalLayout_28.addWidget(self.sensor4_temp_value)
        self.sensor4_temp_trend_btn = QtWidgets.QPushButton(self.sensor4_temp_frame)
        self.sensor4_temp_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor4_temp_trend_btn.setText("")
        self.sensor4_temp_trend_btn.setIcon(icon6)
        self.sensor4_temp_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor4_temp_trend_btn.setObjectName("sensor4_temp_trend_btn")
        self.horizontalLayout_28.addWidget(self.sensor4_temp_trend_btn)
        self.horizontalLayout_27.addWidget(self.sensor4_temp_frame)
        self.sensor4_humidity_frame = QtWidgets.QFrame(self.sensor4_details_frame)
        self.sensor4_humidity_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor4_humidity_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor4_humidity_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor4_humidity_frame.setObjectName("sensor4_humidity_frame")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.sensor4_humidity_frame)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.sensor4_humidity_label = QtWidgets.QLabel(self.sensor4_humidity_frame)
        self.sensor4_humidity_label.setMaximumSize(QtCore.QSize(46, 16777215))
        self.sensor4_humidity_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor4_humidity_label.setObjectName("sensor4_humidity_label")
        self.horizontalLayout_29.addWidget(self.sensor4_humidity_label)
        self.sensor4_humidity_value = QtWidgets.QLabel(self.sensor4_humidity_frame)
        self.sensor4_humidity_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor4_humidity_value.setText("")
        self.sensor4_humidity_value.setObjectName("sensor4_humidity_value")
        self.horizontalLayout_29.addWidget(self.sensor4_humidity_value)
        self.sensor4_humidity_trend_btn = QtWidgets.QPushButton(self.sensor4_humidity_frame)
        self.sensor4_humidity_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor4_humidity_trend_btn.setText("")
        self.sensor4_humidity_trend_btn.setIcon(icon6)
        self.sensor4_humidity_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor4_humidity_trend_btn.setObjectName("sensor4_humidity_trend_btn")
        self.horizontalLayout_29.addWidget(self.sensor4_humidity_trend_btn)
        self.horizontalLayout_27.addWidget(self.sensor4_humidity_frame)
        self.sensor4_CO2_frame = QtWidgets.QFrame(self.sensor4_details_frame)
        self.sensor4_CO2_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor4_CO2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor4_CO2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor4_CO2_frame.setObjectName("sensor4_CO2_frame")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.sensor4_CO2_frame)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.sensor4_co2_label = QtWidgets.QLabel(self.sensor4_CO2_frame)
        self.sensor4_co2_label.setMaximumSize(QtCore.QSize(30, 16777215))
        self.sensor4_co2_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor4_co2_label.setObjectName("sensor4_co2_label")
        self.horizontalLayout_30.addWidget(self.sensor4_co2_label)
        self.sensor4_co2_value = QtWidgets.QLabel(self.sensor4_CO2_frame)
        self.sensor4_co2_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor4_co2_value.setText("")
        self.sensor4_co2_value.setObjectName("sensor4_co2_value")
        self.horizontalLayout_30.addWidget(self.sensor4_co2_value)
        self.sensor4_co2_trend_btn = QtWidgets.QPushButton(self.sensor4_CO2_frame)
        self.sensor4_co2_trend_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.sensor4_co2_trend_btn.setText("")
        self.sensor4_co2_trend_btn.setIcon(icon6)
        self.sensor4_co2_trend_btn.setIconSize(QtCore.QSize(32, 32))
        self.sensor4_co2_trend_btn.setObjectName("sensor4_co2_trend_btn")
        self.horizontalLayout_30.addWidget(self.sensor4_co2_trend_btn)
        self.horizontalLayout_27.addWidget(self.sensor4_CO2_frame)
        self.sensor4_status_frame = QtWidgets.QFrame(self.sensor4_details_frame)
        self.sensor4_status_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(23, 37, 83);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(23, 37, 83);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.sensor4_status_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sensor4_status_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sensor4_status_frame.setObjectName("sensor4_status_frame")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.sensor4_status_frame)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.sensor4_status_label = QtWidgets.QLabel(self.sensor4_status_frame)
        self.sensor4_status_label.setMaximumSize(QtCore.QSize(35, 16777215))
        self.sensor4_status_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor4_status_label.setObjectName("sensor4_status_label")
        self.horizontalLayout_31.addWidget(self.sensor4_status_label)
        self.sensor4_status_value = QtWidgets.QLabel(self.sensor4_status_frame)
        self.sensor4_status_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensor4_status_value.setText("")
        self.sensor4_status_value.setObjectName("sensor4_status_value")
        self.horizontalLayout_31.addWidget(self.sensor4_status_value)
        self.horizontalLayout_27.addWidget(self.sensor4_status_frame)
        self.verticalLayout_15.addWidget(self.sensor4_details_frame)
        self.sensor4_MplWidget = MplWidget(self.sensor4_body)
        self.sensor4_MplWidget.setObjectName("sensor4_MplWidget")
        self.verticalLayout_15.addWidget(self.sensor4_MplWidget)
        self.verticalLayout_14.addWidget(self.sensor4_body)
        self.verticalLayout_16.addWidget(self.sensor4_main_frame)
        self.sensors_stacked_widget.addWidget(self.sensor4_page)
        self.verticalLayout_5.addWidget(self.sensors_stacked_widget)
        self.stackedWidget.addWidget(self.sensors_page)
        self.accounts_page = QtWidgets.QWidget()
        self.accounts_page.setObjectName("accounts_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.accounts_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.accounts_page)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(95, 95, 95);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.accounts_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settings_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.settings_page)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(95, 95, 95);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.settings_page)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.center_main_menu)
        self.verticalLayout.addWidget(self.main_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.sensors_stacked_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sensor1_label.setText(_translate("MainWindow", "WTR-IM"))
        self.sensor1_temp_label.setText(_translate("MainWindow", "Temperature:"))
        self.sensor1_humidity_label.setText(_translate("MainWindow", "Humidity:"))
        self.sensor1_co2_label.setText(_translate("MainWindow", "CO2:"))
        self.sensor1_status_label.setText(_translate("MainWindow", "Status:"))
        self.sensor2_label.setText(_translate("MainWindow", "WTR-IM 2"))
        self.sensor2_temp_label.setText(_translate("MainWindow", "Temperature:"))
        self.sensor2_humidity_label.setText(_translate("MainWindow", "Humidity:"))
        self.sensor2_co2_label.setText(_translate("MainWindow", "CO2:"))
        self.sensor2_status_label.setText(_translate("MainWindow", "Status:"))
        self.sensor3_label.setText(_translate("MainWindow", "WTR-IM 3"))
        self.sensor3_temp_label.setText(_translate("MainWindow", "Temperature:"))
        self.sensor3_humidity_label.setText(_translate("MainWindow", "Humidity:"))
        self.sensor3_co2_label.setText(_translate("MainWindow", "CO2:"))
        self.sensor3_status_label.setText(_translate("MainWindow", "Status:"))
        self.sensor4_label.setText(_translate("MainWindow", "WTR-IM 4"))
        self.sensor4_temp_label.setText(_translate("MainWindow", "Temperature:"))
        self.sensor4_humidity_label.setText(_translate("MainWindow", "Humidity:"))
        self.sensor4_co2_label.setText(_translate("MainWindow", "CO2:"))
        self.sensor4_status_label.setText(_translate("MainWindow", "Status:"))
        self.label_2.setText(_translate("MainWindow", "Accounts Page"))
        self.label_4.setText(_translate("MainWindow", "Settings Page"))
from mplwidget import MplWidget
import demo_rc
