# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(4, 44, 103);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_header.setStyleSheet("QFrame{\n"
"    border-bottom: 1px solid #000;\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.main_header.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tittle_bar_container = QtWidgets.QFrame(self.main_header)
        self.tittle_bar_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tittle_bar_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tittle_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar_container.setObjectName("tittle_bar_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tittle_bar_container)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_menu_toggle = QtWidgets.QFrame(self.tittle_bar_container)
        self.left_menu_toggle.setMinimumSize(QtCore.QSize(50, 0))
        self.left_menu_toggle.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_menu_toggle.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"}")
        self.left_menu_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toggle.setObjectName("left_menu_toggle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.left_menu_toggle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.left_menu_toggle)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.horizontalLayout_5.addWidget(self.left_menu_toggle)
        self.tittle_bar = QtWidgets.QFrame(self.tittle_bar_container)
        self.tittle_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tittle_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar.setObjectName("tittle_bar")
        self.horizontalLayout_5.addWidget(self.tittle_bar)
        self.horizontalLayout_2.addWidget(self.tittle_bar_container)
        self.top_right_btns = QtWidgets.QFrame(self.main_header)
        self.top_right_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.top_right_btns.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.top_right_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_right_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimizeButton = QtWidgets.QPushButton(self.top_right_btns)
        self.minimizeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon1)
        self.minimizeButton.setIconSize(QtCore.QSize(24, 24))
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_3.addWidget(self.minimizeButton)
        self.restoreButton = QtWidgets.QPushButton(self.top_right_btns)
        self.restoreButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreButton.setIcon(icon2)
        self.restoreButton.setIconSize(QtCore.QSize(24, 24))
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout_3.addWidget(self.restoreButton)
        self.closeButton = QtWidgets.QPushButton(self.top_right_btns)
        self.closeButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon3)
        self.closeButton.setIconSize(QtCore.QSize(24, 24))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.horizontalLayout_2.addWidget(self.top_right_btns)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        self.left_side_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_side_menu.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton{\n"
"    padding: 20px 10px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"}")
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.verticalLayout_2.setContentsMargins(7, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_menu_top_buttons = QtWidgets.QFrame(self.left_side_menu)
        self.left_menu_top_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_top_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_top_buttons.setObjectName("left_menu_top_buttons")
        self.formLayout = QtWidgets.QFormLayout(self.left_menu_top_buttons)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.home_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.home_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_button.sizePolicy().hasHeightForWidth())
        self.home_button.setSizePolicy(sizePolicy)
        self.home_button.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setKerning(False)
        self.home_button.setFont(font)
        self.home_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_button.setStyleSheet("background-image: url(:/icons/icons/cil-home.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;\n"
"")
        self.home_button.setDefault(False)
        self.home_button.setObjectName("home_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.home_button)
        self.accounts_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.accounts_button.setMinimumSize(QtCore.QSize(100, 0))
        self.accounts_button.setStyleSheet("background-image: url(:/icons/icons/cil-user.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.accounts_button.setObjectName("accounts_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.accounts_button)
        self.verticalLayout_2.addWidget(self.left_menu_top_buttons)
        self.settings_button = QtWidgets.QPushButton(self.left_side_menu)
        self.settings_button.setMinimumSize(QtCore.QSize(100, 0))
        self.settings_button.setStyleSheet("background-image: url(:/icons/icons/cil-settings.png);\n"
"background-repeat: none;\n"
"padding-left: 50px;\n"
"background-position: center left;")
        self.settings_button.setObjectName("settings_button")
        self.verticalLayout_2.addWidget(self.settings_button)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.center_main_menu = QtWidgets.QFrame(self.main_body)
        self.center_main_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.center_main_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_main_menu.setObjectName("center_main_menu")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.center_main_menu)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.center_main_menu)
        self.stackedWidget.setStyleSheet("QPushButton{\n"
"    background-color: rgb(4, 44, 103);\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 104, 156);\n"
"    border-radius: 5px;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_generate_random_signal = QtWidgets.QPushButton(self.home_page)
        self.pushButton_generate_random_signal.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_generate_random_signal.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_generate_random_signal.setObjectName("pushButton_generate_random_signal")
        self.verticalLayout_5.addWidget(self.pushButton_generate_random_signal, 0, QtCore.Qt.AlignHCenter)
        self.MplWidget = MplWidget(self.home_page)
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout_5.addWidget(self.MplWidget)
        self.stackedWidget.addWidget(self.home_page)
        self.accounts_page = QtWidgets.QWidget()
        self.accounts_page.setObjectName("accounts_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.accounts_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.accounts_page)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(95, 95, 95);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.accounts_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settings_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.settings_page)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(95, 95, 95);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.settings_page)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.center_main_menu)
        self.right_side_menu = QtWidgets.QFrame(self.main_body)
        self.right_side_menu.setMaximumSize(QtCore.QSize(100, 16777215))
        self.right_side_menu.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.right_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_side_menu.setObjectName("right_side_menu")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.right_side_menu)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.right_side_menu)
        font = QtGui.QFont()
        font.setFamily("Autumn")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.horizontalLayout.addWidget(self.right_side_menu)
        self.verticalLayout.addWidget(self.main_body)
        self.main_footer = QtWidgets.QFrame(self.centralwidget)
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 30))
        self.main_footer.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    border-top-color: solid 1px rgb(0, 0, 0);\n"
"}")
        self.main_footer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.verticalLayout.addWidget(self.main_footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.home_button.setText(_translate("MainWindow", "HOME"))
        self.accounts_button.setText(_translate("MainWindow", "ACCOUNT"))
        self.settings_button.setText(_translate("MainWindow", "SETTINGS"))
        self.pushButton_generate_random_signal.setText(_translate("MainWindow", "Generate Random Signal"))
        self.label_2.setText(_translate("MainWindow", "Accounts Page"))
        self.label_4.setText(_translate("MainWindow", "Settings Page"))
        self.label_3.setText(_translate("MainWindow", "RIGHT MENU"))
from mplwidget import MplWidget
import demo_rc
